### ISSUE TITLE
Could not pass event PlayerBucketFillEvent

### ISSUE THREAD

**Issue by AndiSlash0723** [Multiverse/Multiverse-Portals#566]
Server: Paper-138 (1.16.1)
Way to reproduce: Fill a bucket with water.
Multiverse-Portals version: v4.1.1

https://gist.github.com/AndiSlash0723/2516497641875a376df008d3409b0014

`[02:59:49 ERROR]: Could not pass event PlayerBucketFillEvent to Multiverse-Portals v4.1.1-SNAPSHOT-bUNKNOWN
java.lang.NullPointerException: null
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerBucketFill(MVPPlayerListener.java:71) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor182.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-138]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:449) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:425) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.ItemBucket.a(ItemBucket.java:44) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.ItemStack.a(ItemStack.java:379) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:412) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1527) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-138]
        at java.lang.Thread.run(Thread.java:835) [?:?]`

**Comment by nicegamer7** [comment]
This *might* be fixed with #551.

**Comment by AndiSlash0723** [comment]
Sorry I dont understand, since I dont really know how to use GitHub :(
The version I'm using was downloaded in Discord (as long as I remember, not sure if there are any new releases after that)

**Comment by benwoo1110** [comment]
v4.2 have you release on bukkit site. @AndiSlash0723 may I ask if the issue still persist on the latest version of papermc and MV plugins?

**Comment by kutaxoff** [comment]
Yes, the issue still persist on v4.2 plugin version and on 244 paper version (latest version is 246)
```
[13:38:03 ERROR]: Could not pass event PlayerBucketFillEvent to Multiverse-Portals v4.2.0-b826
java.lang.NullPointerException: null
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerBucketFill(MVPPlayerListener.java:70) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor379.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-244]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-244]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-244]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-244]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:454) ~[patched_1.16.3.jar:git-Paper-244]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:430) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.ItemBucket.a(ItemBucket.java:44) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.ItemStack.a(ItemStack.java:379) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:414) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1532) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-244]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```

**Comment by nicegamer7** [comment]
Thanks for letting us know. Can you please explain what you're doing when this happens? Or maybe take a video and show us.

**Comment by kutaxoff** [comment]
I was not able to find an accurate and permanent way to reproduce the error, but it usually occurs when water/lava is collected in a bucket, last time player was collecting lava in second (not default) overworld in several buckets at once, but when I tried to do the same thing, nothing happened. 
P.S. on paper 246 too.

**Comment by nicegamer7** [comment]
Okay, that's fine. We will look into it when time permits.

**Comment by PS1TD** [comment]
I have the same issue. Happens when the player enters a nether portal.

**Comment by ZEROOblivious** [comment]
I have the same problem.

Multiverse-Portals-4.2.0.jar
git-Paper-251

**Comment by AnmolMago** [comment]
I can confirm this error is also happening with the latest **Spigot** and multiverse.

**Comment by benwoo1110** [comment]
For people facing the issue, can you ensure you are on the latest version of mv plugins (v4.2.X) and send your full startup log as well as the output of `/mvversion -p`

**Comment by nicegamer7** [comment]
It would be nice if you included a list of plugins, i.e. `/mvversion -p --include-plugin-list`.

**Comment by Crumb5** [comment]
One player reported that in between essentials:home teleports they crafted a bucket which refunded him 1/3 iron required. The refunded iron disappeared later and the error occurred when the bucket which had been filled with lava was emptied into water

**Comment by aaquino3** [comment]
This is happening on my server as well. When making an iron farm, the iron farm will work. After a while it stops working and when removing the water I get this same error.

**Comment by benwoo1110** [comment]
@aaquino3 @AnmolMago can you please provide your full startup log as well as the link  output of `/mvversion -p`.

**Comment by aaquino3** [comment]
@benwoo1110 

Here is the server log. I removed some lines that contained chats and users logging in due to sensitive info like ip address. No errors happened during that time:  https://pastebin.com/cZN7M4jQ

https://paste.gg/p/anonymous/1ece924dce6540369b4b3fd6cf6299ff

Paper Version: 261
Minecraft: 1.16.4

**Comment by nicegamer7** [comment]
@benwoo1110 figured it out 🥳! This will be fixed by #590.

**Comment by aaquino3** [comment]
@nicegamer7 @benwoo1110 sweet, #590  looks like it needs some approval. When do we expect a build? I don't mind testing it

**Comment by nicegamer7** [comment]
Not too sure when it'll be merged. But for now I've provided a build on the PRs thread.

**Comment by nicegamer7** [comment]
Fixed in Release 4.2.1, thanks to everyone who participated!
